name: Project api and test
on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8'  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install Angular program dependencies, Angular global CLI + ng build
        working-directory: ./frontend
        run: |
          npm i -g @angular/cli
          npm i
          ng build -c="development"

      - name: Build test code and install playwright test browser
        working-directory: ./Test
        run: |
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build and run Web API + getting process ID for shutting down later
        working-directory: ./api
        run: |
          dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Run tests once API is running (sleep interval set to 180 seconds)
        working-directory: ./Test
        run: |
          sleep 180
          dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Shutdown when done running
        run: kill $API_PID
