name: api test with postman with cli
on:
  push:
    branch:
      -development
    pull_request:
      branch:
        - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install Angular program dependencies, Angular global CLI + ng build
        run: cd ./frontend && npm i -g @angular/cli && npm i && ng build -c="development"

#      - name: Build test code and install playwright test browser
#        run: cd ./api/Test && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

#      - name: Build and run Web API + getting process ID for shutting down later
#        run: cd ./api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
#        env:
#          pgconn: ${{secrets.PGCONN}}

#      - name: Run tests once API is running (sleep interval set to 60 seconds)
#        run: cd ./api/Test && sleep 60 && dotnet test
#        env:
#          pgconn: ${{secrets.PGCONN}}
          
#      - name: Shutdown when done running
#        run: kill $API_PID